### ISSUE TITLE
Crashing PhpStorm during indexing

### ISSUE THREAD

**Issue by dawounit** [Haehnchen/idea-php-annotation-plugin#135]
During indexing I'm getting below IDE Fatal Error.
Error message: `com/intellij/util/indexing/IndexId`
Details:
```
com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at de.espend.idea.php.annotation.util.AnnotationUtil.getAnnotationsClasses(AnnotationUtil.java:85)
	at de.espend.idea.php.annotation.util.AnnotationUtil.getPossibleImportClasses(AnnotationUtil.java:391)
	at de.espend.idea.php.annotation.inspection.AnnotationMissingUseInspection.visitAnnotationDocTag(AnnotationMissingUseInspection.java:62)
	at de.espend.idea.php.annotation.inspection.AnnotationMissingUseInspection.access$000(AnnotationMissingUseInspection.java:24)
	at de.espend.idea.php.annotation.inspection.AnnotationMissingUseInspection$1.visitElement(AnnotationMissingUseInspection.java:35)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpASTElementImpl.accept(PhpASTElementImpl.java:32)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:250)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[de.espend.idea.php.annotation, 5.2.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```
Versions:
- PHP Annotation 5.2.1
- PhpStorm 2017.1.5
- Build #PS-171.4694.83, built on March 7, 2018
- JRE: 1.8.0_112-release-736-b22 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Linux 4.15.0-36-generic

**Comment by cedricziel** [comment]
Does the problem still exist? If yes, please reopen the issue. Thanks.
