### ISSUE TITLE
Read access is allowed from event dispatch thread

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-annotation-plugin#37]
```java
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 223,4,main] 32537843
Our dispatch thread:Thread[AWT-EventQueue-0 7.1.1#PS-133.679, eap:false,6,main] 18913093
SystemEventQueueThread: Thread[AWT-EventQueue-0 7.1.1#PS-133.679, eap:false,6,main] 18913093
java.lang.Throwable
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:124)
at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1025)
at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:163)
at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:202)
at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.getFirstChild(LazyParseablePsiElement.java:89)
at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:43)
at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:30)
at com.intellij.util.WalkingState.next(WalkingState.java:73)
at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:70)
at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
at de.espend.idea.php.annotation.AnnotationStubIndex$1$1.visitElement(AnnotationStubIndex.java:58)
at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:32)
at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:141)
at de.espend.idea.php.annotation.AnnotationStubIndex$1.map(AnnotationStubIndex.java:51)
at de.espend.idea.php.annotation.AnnotationStubIndex$1.map(AnnotationStubIndex.java:36)
at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:209)
at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1777)
at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1717)
at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.a(FileBasedIndexImpl.java:2284)
at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.a(FileBasedIndexImpl.java:2235)
at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.access$1600(FileBasedIndexImpl.java:1879)
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:815)
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:785)
at com.intellij.psi.stubs.StubIndexImpl.process(StubIndexImpl.java:240)
at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:219)
at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:209)
at com.jetbrains.php.PhpIndexImpl.getDirectSubclasses(PhpIndexImpl.java:280)
at com.jetbrains.php.PhpIndexImpl.getAllSubclasses(PhpIndexImpl.java:297)
at com.jetbrains.php.PhpIndexImpl.getAllSubclasses(PhpIndexImpl.java:289)
at com.jetbrains.php.PhpClassHierarchyUtils.processOverridingMembers(PhpClassHierarchyUtils.java:222)
at com.jetbrains.php.lang.findUsages.PhpFindUsagesHandlerFactory$1.processInReadAction(PhpFindUsagesHandlerFactory.java:63)
at com.jetbrains.php.lang.findUsages.PhpFindUsagesHandlerFactory.checkImplementedMethods(PhpFindUsagesHandlerFactory.java:60)
at com.jetbrains.php.lang.findUsages.PhpFindUsagesHandler.processElementUsages(PhpFindUsagesHandler.java:77)
at com.intellij.find.findUsages.FindUsagesManager$3.generate(FindUsagesManager.java:436)
at com.intellij.usages.impl.UsageViewManagerImpl$SearchForUsagesRunnable.searchUsages(UsageViewManagerImpl.java:350)
at com.intellij.usages.impl.UsageViewManagerImpl$SearchForUsagesRunnable.run(UsageViewManagerImpl.java:331)
at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:147)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:464)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:373)
at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:420)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:724)
at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:150)
```

**Comment by Haehnchen** [comment]
temporary
