### ISSUE TITLE
DoctrinePropertyOrmAnnotationGenerateAction Error

### ISSUE THREAD

**Issue by ghost** [Haehnchen/idea-php-annotation-plugin#94]
Hello,

I installed version 5.2 in my PHPStorm Build: 2017.2.4 and I continue to get this error:

class with name 'de.espend.idea.php.annotation.doctrine.action.DoctrinePropertyOrmAnnotationGenerateAction' not found [Plugin: de.espend.idea.php.annotation]

I uninstalled and reinstalled with no effect.  I tried adding in the optional dependencies and that does not work either.  Here is the full stack trace:

class with name 'de.espend.idea.php.annotation.doctrine.action.DoctrinePropertyOrmAnnotationGenerateAction' not found [Plugin: de.espend.idea.php.annotation]
com.intellij.diagnostic.PluginException: class with name 'de.espend.idea.php.annotation.doctrine.action.DoctrinePropertyOrmAnnotationGenerateAction' not found [Plugin: de.espend.idea.php.annotation]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:155)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:485)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:473)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:358)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:316)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:47)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:40)
	at com.intellij.codeInsight.generation.actions.GenerateAction.update(GenerateAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:235)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:100)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:341)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:98)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:4467)
	at com.intellij.openapi.editor.impl.EditorImpl.access$9500(EditorImpl.java:137)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.a(EditorImpl.java:3536)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3442)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: de.espend.idea.php.annotation.doctrine.action.DoctrinePropertyOrmAnnotationGenerateAction PluginClassLoader[de.espend.idea.php.annotation, 5.2] com.intellij.ide.plugins.cl.PluginClassLoader@7645d7ed
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
	... 52 more

**Comment by cedricziel** [comment]
A lot has changed since `2017.2.4` - please re-open, if the issue persists.
